Kometa-Team/Quickstart

templates/001-start.html
templates/modals/001-start.html
templates/modals/020-tmdb.html
templates/modals/030-tautulli.html
templates/modals/040-github.html
templates/modals/050-omdb.html
templates/modals/060-mdblist.html
templates/modals/070-notifiarr.html
templates/modals/080-gotify.html
templates/modals/090-webhooks.html
templates/modals/100-anidb.html
templates/modals/110-radarr.html
templates/modals/120-sonarr.html
templates/modals/130-trakt.html
templates/modals/140-mal.html
templates/modals/150-settings.html
templates/modals/160-playlist_files.html

added links per modal
updated start page

added links per modal

---

templates/010-plex.html
templates/015-libraries.html
templates/020-tmdb.html
templates/030-tautulli.html
templates/040-github.html
templates/050-omdb.html
templates/060-mdblist.html
templates/070-notifiarr.html
templates/080-gotify.html
templates/090-webhooks.html
templates/100-anidb.html
templates/110-radarr.html
templates/120-sonarr.html
templates/130-trakt.html
templates/140-mal.html
templates/150-settings.html
templates/160-playlist_files.html
templates/modals/015-libraries.html

fields with * validated have been hidden

hide the validated fields

---

templates/modals/010-plex.html
templates/modals/015-libraries.html
templates/modals/020-tmdb.html
templates/modals/030-tautulli.html
templates/modals/040-github.html
templates/modals/050-omdb.html
templates/modals/060-mdblist.html
templates/modals/070-notifiarr.html
templates/modals/080-gotify.html
templates/modals/090-webhooks.html
templates/modals/100-anidb.html
templates/modals/110-radarr.html
templates/modals/120-sonarr.html
templates/modals/130-trakt.html
templates/modals/140-mal.html
templates/modals/150-settings.html
templates/modals/160-playlist_files.html

Move modals to Wiki links and add some general guidance for each page

Move modals to Wiki links and add some general guidance for each page

---

json-schema/config-schema.json
json-schema/prototype_config.yml
modules/helpers.py
static/local-js/150-settings.js
templates/015-libraries.html
templates/020-tmdb.html
templates/050-omdb.html
templates/150-settings.html
templates/modals/015-libraries.html
templates/modals/090-webhooks.html
templates/modals/150-settings.html

fix for red box and green box on 150-settings

update case for GitHub, OMDb and TMDb

---

modules/output.py
templates/015-libraries.html

nulls removed in final output
015-libraries has reapply_overlays hidden for movies and shows

173 nulls in final output

---

modules/helpers.py
modules/output.py

fixes two issues - redaction and order of libraries section output to be collections, attributes, then overlays

200 update redactor to match kometa

---

.pre-commit-config.yaml
app.py
modules/database.py
modules/persistence.py
templates/001-start.html

Fixes logic in getting the button click to the backend and cleaning stuff out back there

wire up clear button

---

templates/modals/150-settings.html

settings modal color and wording changed

updated wording and color

---

static/local-js/150-settings.js
templates/150-settings.html

any numeric field on this page is now validated in the same way

240 overlay artwork quality bugged

---

modules/output.py
modules/persistence.py
quickstart.py
static/css/styles.css
static/local-js/025-libraries.js
templates/025-libraries.html

use_separator and sep_style implemented per library level
will set use_separators: false by default
if use_separators: true, then chart and award separators are enabled
you get topick your sep_style as well.

244 suggestion set use separator false by default

---

.pre-commit-config.yaml
static/css/styles.css
templates/025-libraries.html

Rework Movie/Show Attributes sections for Separators and Remove/Reset Overlays
Closes #239
Closes #255 
Closes #256

Rework Movie/Show Attributes sections for Separators and Remove/Reset Overlays

---

static/css/styles.css
templates/000-base.html
templates/001-navigation.html
templates/001-start.html
templates/025-libraries.html
templates/900-final.html

Refactored Navigation:
Made hyperlinks blue:

Refactor Navigation & Make Links More Visible

---

templates/000-base.html
templates/001-start.html
templates/modals/001-start.html

Reworded the start page, added warning about Quickstart being in early development and linking to a Discord channel for feedback.
Added some more blurb about the Config Data

rework start page, add test warning

---

static/css/styles.css

CSS tweaks to match the incoming Kometa color changes for background etc:

Color Tweaks to be consistent with new Kometa updates

---

static/local-js/070-notifiarr.js

Please PR this and test the notifiarr page to see if you like the new logic of when to hide or show the "secret" on the page

fix notifiarr hide/unhide password field

---

static/css/styles.css
templates/001-start.html
templates/010-plex.html
templates/020-tmdb.html
templates/025-libraries.html
templates/027-playlist_files.html
templates/030-tautulli.html
templates/040-github.html
templates/050-omdb.html
templates/060-mdblist.html
templates/070-notifiarr.html
templates/080-gotify.html
templates/085-ntfy.html
templates/090-webhooks.html
templates/100-anidb.html
templates/110-radarr.html
templates/120-sonarr.html
templates/130-trakt.html
templates/140-mal.html
templates/150-settings.html
templates/900-final.html

Fixed an issue where floating label headers would disappear when hovered.
Before:
After:
Also consistently using mb-2 spacing so that fields have even spacing between them

Fix Floating Label Disappearing & Use mb-2 padding consistently

---

static/css/styles.css
templates/010-plex.html
templates/020-tmdb.html
templates/027-playlist_files.html
templates/030-tautulli.html
templates/040-github.html
templates/050-omdb.html
templates/060-mdblist.html
templates/070-notifiarr.html
templates/080-gotify.html
templates/085-ntfy.html
templates/090-webhooks.html
templates/100-anidb.html
templates/110-radarr.html
templates/120-sonarr.html
templates/130-trakt.html
templates/140-mal.html
templates/150-settings.html
templates/900-final.html

This PR removes placeholder text for "Enter ..." within floating labels.
I have done a full runthrough and can confirm that this doesn't appear to break any validation and the final YAML is also valid with no unexpected errors.
Before:
After:

Remove placeholder text

---

quickstart.py

Please include a summary of the changes.
- Fixes #(issue)
Please delete options that are not relevant.

test workflows

---

.github/.wordlist.txt
.github/ISSUE_TEMPLATE/1.bug_report.yml
.github/ISSUE_TEMPLATE/2.feature_request.yml
.github/pull_request_template.md

Update GH workflows with changes from Kometa nightly.
Please delete options that are not relevant.

Update GH Workflows

---

static/css/styles.css
static/local-js/025-libraries.js
templates/025-libraries.html

Updated style of the library attributes pages to match new styles, and set max-height of preview overlays image

Update Library Attribute Styles

---

templates/090-webhooks.html

Add Webhook Tooltips

---

templates/010-plex.html
templates/020-tmdb.html

- [] Other 
removed required from certain input boxes on plex and tmdb pages
- Closes #330 
- [] Yes

removed required from certain input boxes on plex and tmdb pages

---

templates/010-plex.html
templates/020-tmdb.html
templates/025-libraries.html
templates/030-tautulli.html
templates/040-github.html
templates/050-omdb.html
templates/060-mdblist.html
templates/070-notifiarr.html
templates/080-gotify.html
templates/085-ntfy.html
templates/090-webhooks.html
templates/100-anidb.html
templates/110-radarr.html
templates/120-sonarr.html
templates/130-trakt.html
templates/140-mal.html
templates/150-settings.html

- [] Other 
- Closes #
- [] Yes
- [] No

Revert button style to not be outline

---

templates/010-plex.html
templates/020-tmdb.html
templates/030-tautulli.html
templates/050-omdb.html
templates/060-mdblist.html
templates/080-gotify.html
templates/085-ntfy.html
templates/090-webhooks.html
templates/100-anidb.html
templates/110-radarr.html
templates/120-sonarr.html
templates/130-trakt.html
templates/140-mal.html

Align Text Label Fields

---

.github/pull_request_template.md
README.md

Add shields

---

modules/helpers.py
quickstart.py
static/css/styles.css
templates/000-base.html

- [] Other 
added version checks
- Closes #355 
- [] Yes

Add version check to Quickstart

---

quickstart.py

- [] Other 
Moved .env to config/
Moved uploads/shows to config/
Moved uploads/movies to config/
- Closes #
- [] Yes

leverage the config/ folder for persistent data

---

modules/validations.py
quickstart.py
static/css/styles.css
static/local-js/090-webhooks.js
templates/000-base.html
templates/001-navigation.html
templates/001-start.html
templates/900-final.html

- [] Other 
bug when an update exists it covers the logo now moved down to resolve
updated navigation buttons
start and final have same navigation as all pages
- Closes #366 
- [] Yes

366 bug when an update exists it covers the logo

---

static/css/styles.css

- [] Other 
Make navbar sticky
- Closes #
- [] Yes

Make navbar sticky

---

.gitignore
Quickstart.spec
modules/database.py
quickstart.py
static/fonts/standard.flf

- [] Other 
First windows installer release completed with pyinstaller
- Closes #356 
- [] Yes

First windows installer release

---

.github/workflows/docker-version.yml
.github/workflows/increment-build.yml

up action version

---

quickstart.py

trigger build

---

Quickstart.spec
modules/helpers.py
modules/persistence.py

- [] Other 
detects branch and then updates url related requests to leverage the branch detected
downloads fresh copy of prototype_config.yml and config-schema.json and config.yml.template and has function to detect changes
- Closes #387 
- [] Yes

387 suggestion move from prototype yml to config template

---

modules/helpers.py
templates/020-tmdb.html
templates/120-sonarr.html
templates/140-mal.html
templates/150-settings.html

sync up missing items from config yml template
- Closes #391 
- [ x] No

391 bug sync up missing items from config yml template

---

quickstart.py
templates/150-settings.html

- [ x ] Bug Fix (non-breaking change which fixes an issue)
hide playlist settings if no shared users
fix save_path for overlays upload button
- Closes #328 
- [ x] No

328 suggestion hide playlist settings if no shared users

---

modules/output.py
quickstart.py

- [ x] Feature/Tweak (non-breaking change which adds new functionality or enhances existing functionality)
added config_name to final output for additional clarity
- Closes #402 
- [x ] No

added config_name to final output for additional clarity

---

templates/085-ntfy.html

fix buggy icons in ntfy page

---

.gitignore
quickstart.py

fix debug mode and icon

---

modules/helpers.py
modules/output.py

ntfy fix and 1-liner fix
- Closes #
- [ x] No

ntfy fix and 1-liner fix

---

quickstart.py

Open quickstart

---

.github/workflows/docker-version.yml

Remove old need and fix release

---

quickstart.py

no tray icon in docker

---

.github/workflows/docker-version.yml
.github/workflows/release-notification.yml
Dockerfile
modules/helpers.py
quickstart.py

fix Docker part2

---

static/local-js/eventHandler.js

dropdown change now bubbles up for the overlay_reset dropdowns
- Closes #429 
- [x ] No

dropdown change now bubbles up for the overlay_reset dropdowns

---

quickstart.py

fix for refresh_plex_libraries
- Closes #430 
- [x ] No

fix for refresh_plex_libraries

---

modules/helpers.py
quickstart.py
requirements.txt

try to make branch and version detection work like kometa
- Closes #
- [x ] No

434 bug git dependency to determine version

---

modules/helpers.py
quickstart.py

try 2 to fix BRANCH_NAME detection
- Closes #
- [x ] No

try 2 to fix BRANCH_NAME detection

---

modules/helpers.py

remove git dependency to determine version and branch
detect QUICKSTART_DOCKER
- Closes #

fix to detect QUICKSTART_DOCKER

---

modules/helpers.py

force update

---

.github/workflows/validate-pull.yml
modules/database.py
modules/helpers.py
modules/output.py
modules/persistence.py
quickstart.py

add formatting

---

.github/workflows/increment-build.yml

add releases folder
- Closes #
- [x ] No

add releases

---

static/local-js/001-start.js
static/local-js/025-libraries.js
static/local-js/eventHandler.js
static/local-js/imageHandler.js
static/local-js/overlayHandler.js
static/local-js/validationHandler.js

test build release
- Closes #
- [x ] No

test build release

---

.github/workflows/increment-build.yml

fix build releases
- Closes #
- [ x ] No

fix build releases

---

static/local-js/eventHandler.js

test fix for release build
- Closes #
- [x ] No

test fix for release build

---

static/local-js/eventHandler.js

trigger the build
- Closes #
- [ x] No

force the build

---

.github/workflows/increment-build.yml

reorder things a bit
- Closes #
- [x ] No

added debug info

---

static/local-js/eventHandler.js

Test reorder for builds
- Closes #
- [x ] No

trigger the build

---

.github/workflows/increment-build.yml

trying to get the builds to work
- Closes #
- [x ] No

with matrix instead

---

.github/workflows/increment-build.yml

update and simplify builde

---

static/local-js/eventHandler.js

Merged builds

---

.github/workflows/increment-build.yml
static/local-js/eventHandler.js

Builds folder

---

.github/workflows/increment-build.yml

as zip files

---

static/local-js/eventHandler.js

trigger build again

---

.github/workflows/increment-build.yml

split it up again

---

.github/workflows/increment-build.yml

add dependency on increment-build

---

static/local-js/eventHandler.js

with increment-build dependency

---

.github/workflows/increment-build.yml

with files wildcard

---

static/local-js/imageHandler.js

trigger the build with file wildcard

---

.github/workflows/increment-build.yml
static/local-js/imageHandler.js

more debugging

---

.github/workflows/increment-build.yml
static/local-js/overlayHandler.js

enhanced ls

---

.github/workflows/increment-build.yml
static/local-js/overlayHandler.js

use pwsh for windows

---

.github/workflows/increment-build.yml
static/local-js/overlayHandler.js

download one per os

---

.github/workflows/increment-build.yml
static/local-js/validationHandler.js

multiple subfolders

---

.github/workflows/increment-build.yml
static/local-js/validationHandler.js

subfolders for release

---

.github/workflows/increment-build.yml
static/local-js/validationHandler.js

use exact filenames

---

.github/workflows/increment-build.yml
quickstart.py

Remove excess lines

---

.github/workflows/docker-version.yml
modules/helpers.py
quickstart.py

Add the ability to change the Port from the tray icon

---

.github/workflows/docker-version.yml
.github/workflows/increment-build.yml

Update GitHub Actions

---

quickstart.py

fix imports

---

quickstart.py

- [ x] Feature/Tweak (non-breaking change which adds new functionality or enhances existing functionality)
trigger build for systray fix
adds port dynamically if default is occupied
adds systray toggle for debug on/off
- Closes #
- [ x] No

trigger build for systray fix

---

modules/helpers.py

- [ x] Feature/Tweak (non-breaking change which adds new functionality or enhances existing functionality)
update_env_variable removed
- Closes #
- [ x] No

update_env_variable removed

---

quickstart.py

port and debug enhancements to systray
- Closes #
- [ x] No

port and debug enhancements to systray

---

templates/partials/_movie_collections.html
templates/partials/_show_overlays.html

fixed broken preview links on libraries page
- Closes #
- [ x] No

fix broken links on libraries page

---

.github/workflows/increment-build.yml
modules/helpers.py

fix git line

---

.github/workflows/increment-build.yml
modules/helpers.py

git changes

---

.github/workflows/docker-version.yml
.github/workflows/increment-build.yml
modules/helpers.py

action update

---

quickstart.py

kill update thread on exit

---

modules/helpers.py
quickstart.py
templates/000-base.html

Fix update links and added icon to the change port popup
- Closes #
- [x ] No

Fix update links

---

quickstart.py

remove tkinter icon
- Closes #
- [x ] No

removed tkinter icon

---

quickstart.py
templates/000-base.html

added Running On: platform
- Closes #
- [x ] No

Add platform to pages

---

quickstart.py
templates/000-base.html

add port check and prep for restart logic
- Closes #
- [x ] No

add port check and prep for restart logic

---

.github/workflows/increment-build.yml
quickstart.py

fix actions

---

.github/workflows/validate-pull.yml

update PR build name

---

static/local-js/eventHandler.js

fix the bug for content_rating_overlays not persisting or being able to unselect on the page or perisist it for the first library only
- Closes #424 
- [x ] No

fix for this bug

---

.github/pull_request_template.md

Reduced wall of text for PR templates, and removed Documentation question as irrelevant

Minimize PR template to reduce wall of text

---

quickstart.py

Fix hover on previous button on last page
- Closes #
- [ x] No

fix hover on previous button on last page

---

templates/modals/001-start.html
templates/partials/_movie_collections.html
templates/partials/_movie_overlays.html
templates/partials/_show_collections.html
templates/partials/_show_overlays.html

This PR will update all image locations for when the docs rework hits Kometa nightly. Once that happens, this PR can be merged.
https://github.com/Kometa-Team/Kometa/pull/2487

(DO NOT MERGE YET) Update Image Pointers

---

modules/output.py
static/json/quickstart_sections.json
static/local-js/eventHandler.js
templates/partials/_macros.html
templates/partials/_movie_attributes.html
templates/partials/_show_attributes.html

library operations genre and content_rating mappers
- Closes #575, #574 
- [ x] No

Add last 2 library operations

---

static/local-js/000-base.js

fix jumpto() to work from 025-libraries
- Closes #584 
- [ x] No

fix for jumpto()

---

modules/output.py

Update output.py with exclude fix
- Closes #
- [ x] No

Update output.py with exclude fix

---

quickstart.py
requirements.txt

- [] Other
Update spec file to include static/json folder for pyinstaller
- Closes #
- [] masOS Executable
- [] Docker
- [] Other

System tray with pyqt

---

quickstart.py

- [] Other
remove strange UTF-8 characters
- Closes #
- [] masOS Executable
- [] Docker
- [] Other

remove strange UTF-8 characters

---

modules/helpers.py

- [] Other
reference static.json in MEI dir for exe
- Closes #
- [] Docker
- [] Other

reference static.json in MEI dir for exe

---

modules/output.py
static/json/quickstart_sections.json
templates/partials/_macros.html
templates/partials/_movie_attributes.html
templates/partials/_show_attributes.html

- [] Other
added library level report_path
- Closes #
- [] Docker
- [] Other

added library level report_path

---

Dockerfile
requirements.txt

- [] Other
- Closes #
- [] Docker
- [] Other

Revert Changes

---

.github/workflows/docker-develop.yml
.github/workflows/docker-latest.yml
Dockerfile
Dockerfile.arm7
quickstart.py

- [] Other
- Closes #
- [] Docker
- [] Other

remove PyQT for arm builds

---

.github/workflows/docker-develop.yml
.github/workflows/docker-latest.yml

- [] Other
- Closes #
- [] Docker
- [] Other

fix builds

---

templates/001-navigation.html

- [] Other
Make nav menu more accessible
- Closes #
- [] Docker
- [] Other

drop now scrollable and adjusts via viewport

---

modules/validations.py
static/css/styles.css
static/local-js/010-plex.js
templates/010-plex.html

- [] Other
plex pass detection on plex page
- Closes #
- [] Docker
- [] Other

added plex pass detection

---

.github/workflows/validate-pull.yml

- [] Other
- Closes #
- [] Docker
- [] Other

require workflow approval

---

modules/output.py
modules/persistence.py

…
- [] Other
better guards if session times out or first time running or on incognito page
- Closes #
- [] Docker
- [] Other

keyerror fix on config_name

---

requirements.txt

dependabot fixes - ruamel
- Closes #
- [] Docker
- [] Other

dependabot updates

---

quickstart.py
static/css/styles.css
static/local-js/900-final.js
templates/900-final.html

- [] Other
v1 of a qs and kometa side by side local install where you can trigger a run of kometa based on the the quickstart created comfig file. Tested in windows only.
- Closes #
- [] Docker
- [] Other

Monitor kometa run

---

static/local-js/000-base.js

- [] Other
make updater background log dark
- Closes #
- [] Docker
- [] Other

make updater background log dark

---

modules/helpers.py
static/local-js/900-final.js
templates/025-libraries.html
templates/900-final.html

- [] Other
added more run commands that were missing like divider, timeout, width
- Closes #
- [] Docker
- [] Other

Additional run commands

---

.github/.wordlist.txt
README.md

- [] Other
update Readme for side by side detaiked install with Kometa
- Closes #
- [] Docker
- [] Other

updated instructions for local side by side with Kometa

---

static/local-js/900-final.js
templates/900-final.html

- [] Other
conditional view of run command based on how qs is running
- Closes #
- [] Other

conditional view of run command based on how qs is running

---

.github/workflows/docker-develop.yml

- [] Other
- Closes #
- [] Docker
- [] Other

remove manifest

---

.github/workflows/docker-latest.yml
.github/workflows/docker-version.yml
.github/workflows/increment-build.yml
.github/workflows/validate-pull.yml

- [] Other
- Closes #
- [] Docker
- [] Other

update all docker builds

---

.github/workflows/validate-pull.yml

- [] Other
- Closes #
- [] Docker
- [] Other

update PR wf

---

.github/workflows/docker-develop.yml
.github/workflows/docker-latest.yml
.github/workflows/docker-version.yml
.github/workflows/increment-build.yml

- [] Other
- Closes #
- [] Docker
- [] Other

remove unused tags

---

requirements.txt

dependabot gitpython updated
- Closes #
- [] Docker
- [] Other

dependabot gitpython updated

---

.github/workflows/copyright.yml
.github/workflows/docker-develop.yml
.github/workflows/docker-latest.yml
.github/workflows/docker-version.yml
.github/workflows/increment-build.yml
.github/workflows/release-hotfix.yml
.github/workflows/release-master.yml
.github/workflows/release-notification.yml
.github/workflows/tag-cleanup.yml
.github/workflows/tag-new-version.yml
.github/workflows/validate-pull.yml

- [] Other
- Closes #
- [] Docker
- [] Other

update workflow names

---

.github/workflows/docker-version.yml
.github/workflows/increment-build.yml

- [] Other
- Closes #
- [] Docker
- [] Other

check for release tag before deleting

---

.github/workflows/increment-build.yml

- [] Other
- Closes #
- [] Docker
- [] Other

fix changelog

---

templates/000-base.html

- [] Other
fix pyinstaller build check
- Closes #
- [] Docker
- [] Other

testing logic for pyinstaller builds

---

.github/workflows/release-notification.yml

- [] Other
- Closes #
- [] Docker
- [] Other

fix notification url

---

.github/workflows/docker-version.yml
.github/workflows/increment-build.yml

- [] Other
- Closes #
- [] Docker
- [] Other

workflow updates

---

modules/helpers.py

- [] Other
fix macos link
- Closes #
- [] Docker
- [] Other

fix macos link

---

quickstart.py
static/local-js/001-start.js

- [] Other
plex test libraries for docker and pyinstaller
- Closes #
- [] Docker
- [] Other

plex test libraries for docker and pyinstaller

---

.github/workflows/docker-version.yml
.github/workflows/increment-build.yml

- [] Other
- Closes #
- [] Docker
- [] Other

change changelog direction

---

quickstart.py

- [] Other
- Closes #
- [] Docker
- [] Other

hotfix test

---

.github/workflows/increment-build.yml
.github/workflows/release-hotfix.yml

- [] Other
- Closes #
- [] Docker
- [] Other

workflow fixes

---

.github/workflows/docker-version.yml
quickstart.py

- [] Other
- Closes #
- [] Docker
- [] Other

update last tag in workflows

---

.github/workflows/increment-build.yml

- [] Other
- Closes #
- [] Docker
- [] Other

fix build changelog

---

.github/workflows/validate-pull.yml

- [] Other
- Closes #
- [] Docker
- [] Other

inherit secrets

---

quickstart.py

- [] Other
fix output from qs uodate to show more details including resukts of an update to pip itself
- Closes #
- [] Docker
- [] Other

fix qs update when pip needs updates

---

quickstart.py

fix purge logic for docker and pyinstaller builds
- Closes #
- [x ] Local Install (Windows/Linux/Mac via `python quickstart.py`)

fix purge route

---

modules/helpers.py
quickstart.py
static/local-js/900-final.js
templates/000-base.html
templates/900-final.html

made kometa and quickstart updaters more robust and consistent
- Closes #

made kometa and qs updater more robust

---

static/local-js/000-base.js

log output now working again for qs updater
- Closes #

updated qs logging

---

static/css/styles.css
templates/001-navigation.html

added active config_name in nav section
- Closes #

 active config_name is available on all pages

---

.envrc
.pre-commit-config.yaml
modules/helpers.py

`section.totalViewSize(libtype='episode')` is orders of magnitude faster than looping through the seasons.
- Related Issue #756

Faster-episode-counts

---

requirements.txt
static/json/quickstart_collections.json

replaced incorrect sort_by with collection_order in multiple collection sections
- Closes #

replaced incorrect sort_by with collection_order
